In [1]:
# import IT_PI is a module
import IT_PI
from scipy.special import erf
import numpy as np

In [2]:
def velocity_profile(y, nu, U, t):
    return U * (1 - erf(y / (2 * np.sqrt(nu * t))))

# Generate synthetic dataset
y_vals = np.linspace(0, 1, 20)
t_vals = np.linspace(5, 10, 20)
U = np.random.uniform(0.5, 1.0, 5)
nu = np.random.uniform(1e-3, 1e-2, 5)
u_array = []
params = []

for u0, n0 in zip(U, nu):
    for y in y_vals:
        for t in t_vals:
            u_array.append(velocity_profile(y, n0, u0, t))
            params.append([u0, y, t, n0])
u_array = np.array(u_array).reshape(-1, 1)
params = np.array(params)

In [3]:
# Define inputs and outputs
Y = u_array / params[:, 0].reshape(-1, 1)  # Output Pi_o = u/U
X = params                                 # Dimensional input list q
variables = ['U', 'y', 't', '\\nu']        # Variable names
D_in = np.matrix('1 1 0 2; -1 0 1 -1')     # Dimension matrix
num_input = 1


In [4]:
# Run IT_PI
results = IT_PI.main(
    X,
    Y,
    D_in,
    variables=variables,
    num_input=num_input,
    estimator="kraskov",
    estimator_params={"k": 5},
    seed=42
)

Rank of D_in: 2
D_in matrix:
 [[ 1  1  0  2]
 [-1  0  1 -1]]
Basis vectors:
matrix([[-1.,  1., -1.,  0.],
        [ 1.,  1.,  0., -1.]])
------------------------------------------------------------
num of parameters: 2

Using estimator: 'kraskov' with hyperparameters: {'k': 5}

(150_w,300)-aCMA-ES (mu_w=78.0,w_1=3%) in dimension 2 (seed=42, Mon Jul 14 12:59:31 2025)
Iterat #Fevals   function value  axis ratio  sigma  min&max std  t[m:s]
    1    300 -2.827282858421731e+00 1.0e+00 7.68e-01  5e-01  7e-01 0:00.9
    2    600 -2.928039452764305e+00 2.0e+00 8.38e-01  3e-01  5e-01 0:01.9
    3    900 -3.356550234238555e+00 4.1e+00 9.34e-01  2e-01  3e-01 0:02.9
    6   1800 -3.436320622681203e+00 1.2e+01 1.38e+00  8e-02  8e-02 0:06.2
   10   3000 -3.592994469256992e+00 4.9e+01 2.82e+00  3e-02  3e-02 0:10.5
   15   4500 -3.597974374995223e+00 1.8e+02 3.05e+00  3e-03  3e-03 0:15.8
   21   6300 -3.598087413740079e+00 2.5e+02 4.94e+00  6e-04  6e-04 0:22.0
   26   7800 -3.598234504731816e+00 1.4e+

In [5]:
# Display results
print("\nOptimal dimensionless variable(s):", results["labels"])
print("Irreducible error:", results["irreducible_error"])
print("Uncertainty:", results["uncertainty"])


Optimal dimensionless variable(s): ['$\\frac{y^{1.0}}{t^{0.5} \\cdot \\nu^{0.5}}$']
Irreducible error: [0.09503666218048899]
Uncertainty: [0.05489068879854224]
